server:
  port: 8080

spring:
  security:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb+srv://nikhilkoli:AJdS9w3a9Tkh4tqK@restaurantservicecluste.gcrua.mongodb.net/users?retryWrites=true&w=majority&appName=RestaurantServiceCluster
foursquare:
  api:
    key: fsq3nELtIPixx7Mt3uRIaecINJuarCRZYixZeXUsisPkqW8=
google:
  places:
    api:
      key: AIzaSyBJFqNCA6pUX6vzWOnJtI7LQWi6UGJUr6M
