spring:
  datasource:
    url: jdbc:mysql://userservice.cvkoqyi2aeyb.us-west-1.rds.amazonaws.com/userservice
    username: admin
    password: techTitans#202
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicTypeRegistry: TRACE
server:
  port: 8081